#!/bin/bash
# Copyright 2024 Robotnik Automation S.L.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    1. Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#
#    2. Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
#    3. Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Maintanier: Rafael Martin  <rmartin@robotnik.es> Robotnik Automation S.L.

set -e

GRUB_CFG="/boot/grub/grub.cfg"

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "Error: This script must be run as root"
    exit 1
fi

# Check if the GRUB_CFG file exists
if [ ! -f "$GRUB_CFG" ]; then
    echo "Error: $GRUB_CFG file not found"
    exit 1
fi

# Get the boot menu entries
echo "Boot menu entries:"

gawk 'BEGIN {
  l=0
  menuindex= 0
  stack[t=0] = 0
}

function push(x) { stack[t++] = x }

function pop() { if (t > 0) { return stack[--t] } else { return "" }  }

{

if( $0 ~ /.*menu.*{.*/ )
{
  push( $0 )
  l++;

} else if( $0 ~ /.*{.*/ )
{
  push( $0 )

} else if( $0 ~ /.*}.*/ )
{
  X = pop()
  if( X ~ /.*menu.*{.*/ )
  {
     l--;
     match( X, /^[^'\'']*'\''([^'\'']*)'\''.*$/, arr )

     if( l == 0 )
     {
       print menuindex ": " arr[1]
       menuindex++
       submenu=0
     }
  }
}

}' $GRUB_CFG
